version: "3.8"
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: anurag
      POSTGRES_PASSWORD: anurag123
      POSTGRES_DB: contactDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anurag"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

volumes:
  pgdata:
