version: "3.8"
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
      - DB_HOST=postgres

volumes:
  pgdata:
