version: "3.8"
services:
  postgres-dev:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    env_file:
      - .env

  web-dev:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - postgres-dev
    env_file:
      - .env

volumes:
  pgdata-dev: