version: "3.8"
services:
  postgres-prod:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    env_file:
      - .env

  web-prod:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - postgres-prod
    env_file:
      - .env

volumes:
  pgdata-prod: